CREATE TABLE SUPPLIER(
sno TEXT,
sname TEXT,
status INT,
city TEXT
);
SELECT * FROM SUPPLIER;
INSERT INTO SUPPLIER(sno,sname,status,city) VALUES
("S1","PALLAB",20,"MUMBAI"),
("S2","OMAR",30,"LONDON"),
("S4","JHON",20,"RAJASTHAN"),
("S5","RAHUL",10,"GUJRAT"),
("S6","DHONI",10,"HIMALAY"),
("S7","ROHIT",60,"DHIGA"),
("S8","RAKESH",40,"KHANAKUL"),
("S9","DEBJIT",50,"DHAKA"),
("S10","PIYALI",20,"KOLKATA"),
("S11","PUJA",20,"ATHENS"),
("S12","SUMON",30,"PARIS");
