CREATE TABLE MYSTUDENTS(
id INT,
name VARCHAR(100),
grade VARCHAR(10),
marks DECIMAL(5,2)
);
INSERT INTO MYSTUDENTS(id,name,grade,marks) VALUES
(1,"PALLAB","C",85.50);
SELECT * FROM MYSTUDENTS;
INSERT INTO MYSTUDENTS(id,name,grade,marks) VALUES
(1,"OMAR","A",99.50);
INSERT INTO MYSTUDENTS(id,name,grade,marks) VALUES
(1,"JHON","B",71.50);
INSERT INTO MYSTUDENTS(id,name,grade,marks) VALUES
(1,"RAHUL","D",91.50);